"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import dj_database_url
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6*@zu1@@mriy5l+@ko6!+2@ss)x@ef@==2tf%m2s66i-)tz1*m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '10.92.1.13'] # Obrigatório quando Debug é False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'core',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.microsoft',
    'django_browser_reload',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_browser_reload.middleware.BrowserReloadMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'setup.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'setup.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Se tiver a variável DATABASE_URL (no Docker tem), usa ela. Se não, usa SQLite.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DATABASE_NAME'),  # (confira se bate com o docker-compose)
        'USER': os.environ.get('DATABASE_USER'),   # (confira se bate com o docker-compose)
        'PASSWORD': os.environ.get('DATABASE_PASSWORD'), # (confira se bate com o docker-compose)
        'HOST': os.environ.get('DATABASE_HOST'),        # <--- AQUI É O PULO DO GATO! NÃO USE LOCALHOST.
        'PORT': os.environ.get('DATABASE_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'core', 'static'),
]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'core.Employee'

LOGIN_REDIRECT_URL = 'home'
LOGIN_URL = 'login'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend', # Login padrão
    'allauth.account.auth_backends.AuthenticationBackend', # Login Microsoft
]

# Configurações do Allauth
ACCOUNT_EMAIL_VERIFICATION = "none" # Não pedir pra confirmar e-mail (agiliza)
SOCIALACCOUNT_LOGIN_ON_GET = True # Logar direto sem tela intermediária

# As chaves que pegamos no Azure (SUBSTITUA PELAS SUAS!)
SOCIALACCOUNT_PROVIDERS = {
    'microsoft': {
        'APP': {
            'client_id': os.environ.get('MICROSOFT_CLIENT_ID'),
            'secret': os.environ.get('MICROSOFT_SECRET_KEY'),
            'key': ''
        },
        'TENANT': os.environ.get('TENANT_ID'),


        'SCOPE': ['User.Read', 'profile', 'openid', 'email'],
        
        'AUTH_PARAMS': {
            'prompt': 'select_account',
        },
        
        # 3. Garante que estamos usando o protocolo moderno
        'METHOD': 'oauth2',
        'VERIFIED_EMAIL': True,
    }
}

STATIC_URL = 'static/'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# settings.py

# 1. Tenta pular o formulário usando os dados do provedor
SOCIALACCOUNT_AUTO_SIGNUP = True

# 2. Ignora a verificação de e-mail (confia que a Microsoft já verificou)
ACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"

# 3. Se o e-mail já existir no banco, conecta automaticamente sem perguntar
# (Cuidado: só use se confiar 100% que o dono do e-mail Microsoft é o mesmo da conta local)
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

# 4. (O Pulo do Gato) Gera um username aleatório se der conflito, para não travar na tela
ACCOUNT_ADAPTER = "core.adapters.MyAccountAdapter"
SOCIALACCOUNT_ADAPTER = "core.adapters.MySocialAccountAdapter"