apiVersion: apps/v1
kind: Deployment
metadata:
  name: estoque-nginx
  namespace: lab-tjce-bqzsv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: estoque-nginx
  template:
    metadata:
      labels:
        app: estoque-nginx
    spec:
      containers:
      - name: nginx
        image: kaikeclear/estoque-app:v3
        ports:
        - containerPort: 8000