apiVersion: apps/v1
kind: Deployment
metadata:
  name: supply-app
  namespace: lab-tjce-bqzsv
spec:
  replicas: 2
  selector:
    matchLabels:
      app: supply-app
  template:
    metadata:
      labels:
        app: supply-app
    spec:
      containers:
      # 1. O Contêiner do Django (Python)
      - name: web
        image: kaikeclear/estoque-app:v3 # <-- TROQUEI PARA A IMAGEM QUE VOCÊ ACABOU DE CRIAR!
        
        # Se você já tiver criado esses arquivos no K8s, ótimo. Se não, eles vão dar erro (leia abaixo).
        envFrom:
        - configMapRef:
            name: supply-config
        - secretRef:
            name: supply-secrets
            
        # AQUI ENTRAM AS VARIÁVEIS QUE FALTAVAM PARA O BANCO DE DADOS!
        env:
        - name: DATABASE_NAME
          value: "postgres_db_stock"
        - name: DATABASE_USER
          value: "clear_stock"
        - name: DATABASE_PASSWORD
          value: "postgres_cleardb123"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_HOST
          value: "postgres-service" # Lembre de trocar pelo nome real do Service do seu Postgres!
          
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: static-data
          mountPath: /app/static

      # 2. O Contêiner do Nginx (Reverse Proxy) - Mantém exatamente igual!
      - name: nginx
        image: kaikeclear/supply-nginx:v1 
        ports:
        - containerPort: 80
        volumeMounts:
        - name: static-data
          mountPath: /app/static

      volumes:
      - name: static-data
        emptyDir: {}