apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - supply-config.yaml      
  - supply-secrets.yaml      
  - supply-app-service.yaml
  - supply-app-deployment.yaml
  - network.yaml
  - nginx-configmap.yaml