upstream hello_django {
    server 127.0.0.1:9000;
}

server {
    listen 80;

    # Onde os arquivos estáticos vivem (mapeado pelo volume)
    location /static/ {
        alias /app/static/;
    }

    # Onde os arquivos de media vivem
    location /media/ {
        alias /app/media/;
    }

    # Tudo que não for estático vai para o Django (Gunicorn)
    location / {
        proxy_pass http://hello_django;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
}