apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: lab-tjce-bqzsv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres # Changed this from 'web'
        image: postgres:15 # THE FIX: Using the official Database image!
        env:
        # We explicitly define the Postgres variables so it creates the right database on boot
        - name: POSTGRES_DB
          value: "postgres_db_stock"
        - name: POSTGRES_USER
          value: "clear_stock"
        - name: POSTGRES_PASSWORD
          value: "postgres_cleardb123"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres # <--- THIS IS YOUR DATABASE'S NETWORK NAME!
  namespace: lab-tjce-bqzsv
spec:
  ports:
  - port: 5432
  selector:
    app: postgres