apiVersion: v1
kind: Secret
metadata:
  name: supply-secrets
  namespace: lab-tjce-bqzsv
type: Opaque
stringData: # O Kubernetes vai converter isso em base64 automaticamente ao aplicar
  MICROSOFT_SECRET_KEY: "H2U8Q~ZwVEEaUOQoB2S_u~6aW1TztXGHHMsh2bT2"
  DATABASE_PASSWORD: "postgres_cleardb123"
  POSTGRES_PASSWORD: "postgres_cleardb123"
  DATABASE_USER: "clear_stock"
  DATABASE_URL: "postgres://clear_stock:postgres_cleardb123@postgres:5432/postgres_db_stock"
  RESERVATION_WEBHOOK_URL: "https://hook.us2.make.com/xfi4gbxbq6ilujm8sf2msm192xvmgyri"