apiVersion: apps/v1
kind: Deployment
metadata:
  name: supply-app
  namespace: lab-tjce-bqzsv
spec:
  replicas: 2
  selector:
    matchLabels:
      app: supply-app
  template:
    metadata:
      labels:
        app: supply-app
    spec:
      containers:
      # 1. O Contêiner do Django (Python)
      - name: web
        image: kaikeclear/estoque-app:v3 # <-- TROQUEI PARA A IMAGEM QUE VOCÊ ACABOU DE CRIAR!
        
        # Se você já tiver criado esses arquivos no K8s, ótimo. Se não, eles vão dar erro (leia abaixo).
        envFrom:
        - configMapRef:
            name: supply-config
        - secretRef:
            name: supply-secrets
          
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: static-data
          mountPath: /app/static

      # 2. O Contêiner do Nginx (Reverse Proxy) - Mantém exatamente igual!
      - name: nginx
        image: kaikeclear/supply-nginx:v1 
        ports:
        - containerPort: 80
        volumeMounts:
        - name: static-data
          mountPath: /app/static

      volumes:
      - name: static-data
        emptyDir: {}