# Generated by Django 4.2.11 on 2026-02-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID do Produto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, default=1111, max_length=255, verbose_name='Modelo'),
            preserve_default=False,
        ),
    ]
