# Generated by Django 6.0.1 on 2026-02-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_product_id_alter_product_manufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockout',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
