# Generated by Django 6.0.1 on 2026-02-03 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_stockout_observation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockout',
            name='out_type',
        ),
        migrations.RemoveField(
            model_name='stockout',
            name='responsible_name',
        ),
        migrations.AddField(
            model_name='stockout',
            name='movement_type',
            field=models.CharField(choices=[('SAIDA', 'Saída Padrão'), ('RESERVA', 'Reserva Técnica'), ('EMPRESTIMO', 'Empréstimo'), ('DESCARTE', 'Descarte/Quebra')], default='SAIDA', max_length=20, verbose_name='Tipo de Movimentação'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Prevista/Agendada'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='location',
            field=models.CharField(choices=[('SP', 'São Paulo'), ('MAO', 'Manaus')], max_length=3),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
