# Generated by Django 6.0.1 on 2026-02-03 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_stockout_out_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockentry',
            name='invoice',
        ),
        migrations.AddField(
            model_name='stockentry',
            name='nf_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nota Fiscal'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='entry_type',
            field=models.CharField(choices=[('COMPRA', 'Compra (Fornecedor)'), ('RETORNO', 'Retorno de Empréstimo'), ('AJUSTE', 'Ajuste de Inventário'), ('DOACAO', 'Doação/Brinde')], default='COMPRA', max_length=20, verbose_name='Tipo de Entrada'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='location',
            field=models.CharField(choices=[('SP', 'São Paulo'), ('MAO', 'Manaus')], max_length=3),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
