# Generated by Django 5.2.11 on 2026-02-19 16:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_stockentry_invoice_stockentry_nf_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockout',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelada em'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_stockouts', to=settings.AUTH_USER_MODEL, verbose_name='Cancelada por'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Cancelada'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID do Produto'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='employee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='nf_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nota Fiscal'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Prevista'),
        ),
        migrations.CreateModel(
            name='ReservationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(blank=True, choices=[('CONFIRMED', 'Retirada Confirmada'), ('CANCELLED', 'Não Utilizado')], max_length=20, null=True)),
                ('stock_out', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_token', to='core.stockout')),
            ],
            options={
                'verbose_name': 'Token de Confirmação',
                'verbose_name_plural': 'Tokens de Confirmação',
            },
        ),
    ]
